apiVersion: v1
kind: Template

labels:
  application: game-server

metadata:
  name: game-server

parameters:
  - name: APPLICATION_NAME
    value: game-server
    required: true
  - name: SECRET_NAME
    value: 2021-demo-common
    required: true
  - name: CONFIG_MAP_NAME
    value: 2021-demo-common
    required: true
  - name: REPLICAS
    value: "1"
    required: true
  - name: HTTP_PORT
    value: "8080"
    required: true
  - name: IMAGE_REPOSITORY
    value: quay.io/redhatdemo/2021-game-server:latest
    required: true
  - name: CONTAINER_REQUEST_CPU
    value: 1000m
  - name: CONTAINER_REQUEST_MEMORY
    value: 1024Mi
  - name: CONTAINER_LIMIT_CPU
    value: 1000m
  - name: CONTAINER_LIMIT_MEMORY
    value: 1024Mi
  - name: ROLLOUT_STRATEGY
    value: "Rolling"
    required: true
  - name: AWS_ACCESS_KEY_ID
    value: ""
  - name: AWS_SECRET_ACCESS_KEY
    value: ""


objects:
  - apiVersion: v1
    kind: DeploymentConfig
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        app.openshift.io/runtime: nodejs
        app: ${APPLICATION_NAME}
    spec:
      replicas: ${{REPLICAS}}
      selector:
        deploymentconfig: ${APPLICATION_NAME}
      strategy:
        type: ${ROLLOUT_STRATEGY}
      template:
        metadata:
          labels:
            app: ${APPLICATION_NAME}
            deploymentconfig: ${APPLICATION_NAME}
        spec:
          containers:
            - env:
              - name: AWS_ACCESS_KEY_ID
                value: ${AWS_ACCESS_KEY_ID}
              - name: AWS_SECRET_ACCESS_KEY
                value: ${AWS_SECRET_ACCESS_KEY}
              - name: AI_AGENT_SERVER_URL
                value: http://ai-agent-server.ai.svc.cluster.local:8080/agent
              envFrom:
                - secretRef:
                    name: ${SECRET_NAME}
                - configMapRef:
                    name: ${CONFIG_MAP_NAME}
              image: ${IMAGE_REPOSITORY}
              imagePullPolicy: Always
              name: ${APPLICATION_NAME}
              ports:
                - containerPort: 8080
                  protocol: TCP
              resources:
                requests:
                  cpu: ${CONTAINER_REQUEST_CPU}
                  memory: ${CONTAINER_REQUEST_MEMORY}
                limits:
                  cpu: ${CONTAINER_LIMIT_CPU}
                  memory: ${CONTAINER_LIMIT_MEMORY}
              terminationMessagePath: /dev/termination-log
              terminationMessagePolicy: File
              readinessProbe:
                tcpSocket:
                  port: ${{HTTP_PORT}}
                initialDelaySeconds: 15
                timeoutSeconds: 5
              livenessProbe:
                tcpSocket:
                  port: ${{HTTP_PORT}}
                initialDelaySeconds: 15
                timeoutSeconds: 5
          dnsPolicy: ClusterFirst
          restartPolicy: Always
          schedulerName: default-scheduler
          securityContext: {}
          terminationGracePeriodSeconds: 30
      test: false
      triggers:
        - type: ConfigChange

  - apiVersion: v1
    kind: Service
    metadata:
      name: ${APPLICATION_NAME}
      labels:
        app: ${APPLICATION_NAME}
    spec:
      ports:
        - name: 8080-tcp
          port: 8080
          protocol: TCP
          targetPort: 8080
      selector:
        deploymentconfig: ${APPLICATION_NAME}
  
  - apiVersion: v1
    kind: Route
    metadata:
      labels:
        app: ${APPLICATION_NAME}
      name: ${APPLICATION_NAME}
    spec:
      port:
        targetPort: 8080
      to:
        kind: Service
        name: ${APPLICATION_NAME}